#lang info

;; pkg metadata
(define deps '("base"))

;; color scheme
(define base00 #(28 31 32))
(define base01 #(235 226 211))
(define base02 #(222 133 73))
(define base03 #(20 20 20))
(define base04 #(204 183 147))
(define base05 #(204 183 147))
(define base06 #(203 129 149))
(define base07 #(141 126 112))
(define base08 #(217 56 38))
(define base09 #(204 183 147))
(define base0A #(160 110 59))
(define base0B #(163 175 98))
(define base0C #(121 168 157))
(define base0D #(204 183 147))
(define base0E #(225 101 95))
(define base0F #(165 86 190))

(define framework:color-schemes
  `(#hash((name . "Gruvbox")
          (white-on-black-base? . #t)
          (colors
           .
	   ((drracket:syncheck:matching-identifiers            ,base03)
            (framework:basic-canvas-background                 ,base00)
            (framework:default-text-color                      ,base01)
            (framework:misspelled-text-color                   ,base08)
            (framework:paren-match-color                       ,base03)
            (drracket:check-syntax:both-obligation-style-pref  ,base0F)
            (drracket:check-syntax:free-variable               ,base0E)
            (drracket:check-syntax:imported                    ,base0D)
            (drracket:check-syntax:lexically-bound             ,base0C)
            (drracket:check-syntax:my-obligation-style-pref    ,base09)
            (drracket:check-syntax:set!d                       ,base0B)
            (drracket:check-syntax:their-obligation-style-pref ,base0A)
            (drracket:check-syntax:unk-obligation-style-pref   ,base08)
            (drracket:check-syntax:unused-require              ,base08)
            (drracket:read-eval-print-loop:error-color         ,base08)
            (drracket:read-eval-print-loop:out-color           ,base09)
            (drracket:read-eval-print-loop:value-color         ,base06)
            (framework:syntax-color:scheme:comment             ,base07)
            (framework:syntax-color:scheme:constant            ,base06)
            (framework:syntax-color:scheme:error               ,base08)
            (framework:syntax-color:scheme:hash-colon-keyword  ,base0C)
            (framework:syntax-color:scheme:keyword             ,base0E bold)
            (framework:syntax-color:scheme:other               ,base02)
            (framework:syntax-color:scheme:parenthesis         ,base04)
            (framework:syntax-color:scheme:string              ,base0B)
            (framework:syntax-color:scheme:symbol              ,base0D)
            (framework:syntax-color:scheme:text                ,base01)
            (plt:htdp:test-coverage-off                        ,base08)
            (plt:htdp:test-coverage-on                         ,base0B)
            (plt:module-language:test-coverage-off             ,base08)
            (plt:module-language:test-coverage-on              ,base0B))))))
