#lang info

;; pkg metadata
(define deps '("base"))

;; color scheme
(define base00 #(37 40 48))
(define base01 #(38 35 42))
(define base02 #(88 82 96))
(define base03 #(22 26 31))
(define base04 #(125 120 137))
(define base05 #(223 225 230))
(define base06 #(209 154 102))
(define base07 #(112 120 137))
(define base08 #(228 12 55))
(define base09 #(97 175 239))
(define base0A #(160 110 59))
(define base0B #(152 195 121))
(define base0C #(224 108 107))
(define base0D #(171 178 191))
(define base0E #(198 120 221))
(define base0F #(191 64 191))

(define framework:color-schemes
  `(#hash((name . "Atom")
          (white-on-black-base? . #t)
          (colors
           .
	   ((drracket:syncheck:matching-identifiers            ,base03)
            (framework:basic-canvas-background                 ,base00)
            (framework:default-text-color                      ,base0D)
            (framework:misspelled-text-color                   ,base0D)
            (framework:paren-match-color                       ,base03)
            (drracket:check-syntax:both-obligation-style-pref  ,base0F)
            (drracket:check-syntax:free-variable               ,base0E)
            (drracket:check-syntax:imported                    ,base0D)
            (drracket:check-syntax:lexically-bound             ,base0C)
            (drracket:check-syntax:my-obligation-style-pref    ,base09)
            (drracket:check-syntax:set!d                       ,base0B)
            (drracket:check-syntax:their-obligation-style-pref ,base0A)
            (drracket:check-syntax:unk-obligation-style-pref   ,base08)
            (drracket:check-syntax:unused-require              ,base08)
            (drracket:read-eval-print-loop:error-color         ,base08)
            (drracket:read-eval-print-loop:out-color           ,base09)
            (drracket:read-eval-print-loop:value-color         ,base0D)
            (framework:syntax-color:scheme:comment             ,base07)
            (framework:syntax-color:scheme:constant            ,base06)
            (framework:syntax-color:scheme:error               ,base08)
            (framework:syntax-color:scheme:hash-colon-keyword  ,base0C)
            (framework:syntax-color:scheme:keyword             ,base0E bold)
            (framework:syntax-color:scheme:other               ,base05)
            (framework:syntax-color:scheme:parenthesis         ,base04)
            (framework:syntax-color:scheme:string              ,base0B)
            (framework:syntax-color:scheme:symbol              ,base0D)
            (framework:syntax-color:scheme:text                ,base05)
            (plt:htdp:test-coverage-off                        ,base08)
            (plt:htdp:test-coverage-on                         ,base0B)
            (plt:module-language:test-coverage-off             ,base08)
            (plt:module-language:test-coverage-on              ,base0B))))))
